# development:
#   <<: *default
#   database: db/taskMateDev.sqlite3


default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['TASKMATE_DEV_DATABASE_USER'] %>
  password: <%= ENV['TASKMATE_DEV_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: taskmate_dev
